import image1_1 from './assets/scribble/MindMatter/1.png'
import image1_2 from './assets/scribble/Overload/1.png'
import image1_3 from './assets/scribble/Tales/1.png'
import image1_4 from './assets/scribble/PeachesAndStrawbs/1.png'
import image1_5 from './assets/scribble/Abstract/1.png'
import image1_6 from './assets/scribble/Unfinished/1.png'
import image1_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image1_8 from './assets/scribble/Resonate/1.png'
import image2_1 from './assets/scribble/MindMatter/2.png'
import image2_2 from './assets/scribble/Overload/2.png'
import image2_3 from './assets/scribble/Tales/2.png'
import image2_4 from './assets/scribble/PeachesAndStrawbs/2.png'
import image2_5 from './assets/scribble/Abstract/2.png'
import image2_6 from './assets/scribble/Unfinished/2.png'
import image2_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image2_8 from './assets/scribble/Resonate/2.png'
import image3_1 from './assets/scribble/MindMatter/3.png'
import image3_2 from './assets/scribble/Overload/3.png'
import image3_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image3_4 from './assets/scribble/PeachesAndStrawbs/3.png'
import image3_5 from './assets/scribble/Abstract/3.png'
import image3_6 from './assets/scribble/Unfinished/3.png'
import image3_7 from './assets/scribble/Wasteland/3.png'
import image3_8 from './assets/scribble/Resonate/3.png'
import image4_1 from './assets/scribble/MindMatter/4.png'
import image4_2 from './assets/scribble/Overload/4.png'
import image4_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image4_4 from './assets/scribble/PeachesAndStrawbs/4.png'
import image4_5 from './assets/scribble/Abstract/4.png'
import image4_6 from './assets/scribble/Unfinished/4.png'
import image4_7 from './assets/scribble/Wasteland/4.png'
import image4_8 from './assets/scribble/Resonate/4.png'
import image5_1 from './assets/scribble/MindMatter/5.png'
import image5_2 from './assets/scribble/Overload/5.png'
import image5_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image5_4 from './assets/scribble/PeachesAndStrawbs/5.png'
import image5_5 from './assets/scribble/Abstract/5.png'
import image5_6 from './assets/scribble/Unfinished/5.png'
import image5_7 from './assets/scribble/Wasteland/5.png'
import image5_8 from './assets/scribble/Resonate/5.png'
import image6_1 from './assets/scribble/MindMatter/6.png'
import image6_2 from './assets/scribble/Overload/6.png'
import image6_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image6_4 from './assets/scribble/PeachesAndStrawbs/6.png'
import image6_5 from './assets/scribble/Abstract/6.png'
import image6_6 from './assets/scribble/Unfinished/6.png'
import image6_7 from './assets/scribble/Wasteland/6.png'
import image6_8 from './assets/scribble/Resonate/6.png'
import image7_1 from './assets/scribble/MindMatter/7.png'
import image7_2 from './assets/scribble/Overload/7.png'
import image7_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image7_4 from './assets/scribble/PeachesAndStrawbs/7.png'
import image7_5 from './assets/scribble/Abstract/7.png'
import image7_6 from './assets/scribble/Unfinished/7.png'
import image7_7 from './assets/scribble/Wasteland/7.png'
import image7_8 from './assets/scribble/Resonate/7.png'
import image8_1 from './assets/scribble/MindMatter/8.png'
import image8_2 from './assets/scribble/Overload/8.png'
import image8_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image8_4 from './assets/scribble/PeachesAndStrawbs/8.png'
import image8_5 from './assets/scribble/Abstract/8.png'
import image8_6 from './assets/scribble/Unfinished/8.png'
import image8_7 from './assets/scribble/Wasteland/8.png'
import image8_8 from './assets/scribble/Resonate/8.png'
import image9_1 from './assets/scribble/MindMatter/9.png'
import image9_2 from './assets/scribble/Overload/9.png'
import image9_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image9_4 from './assets/scribble/PeachesAndStrawbs/9.png'
import image9_5 from './assets/scribble/Abstract/9.png'
import image9_6 from './assets/scribble/Unfinished/9.png'
import image9_7 from './assets/scribble/Wasteland/9.png'
import image9_8 from './assets/scribble/Resonate/9.png'
import image10_1 from './assets/scribble/MindMatter/10.png'
import image10_2 from './assets/scribble/Overload/10.png'
import image10_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image10_4 from './assets/scribble/PeachesAndStrawbs/10.png'
import image10_5 from './assets/scribble/Abstract/10.png'
import image10_6 from './assets/scribble/Unfinished/10.png'
import image10_7 from './assets/scribble/Wasteland/10.png'
import image10_8 from './assets/scribble/Resonate/10.png'
import image11_1 from './assets/scribble/MindMatter/11.png'
import image11_2 from './assets/scribble/Overload/11.png'
import image11_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image11_4 from './assets/scribble/PeachesAndStrawbs/11.png'
import image11_5 from './assets/scribble/Abstract/11.png'
import image11_6 from './assets/scribble/Unfinished/11.png'
import image11_7 from './assets/scribble/Wasteland/11.png'
import image11_8 from './assets/scribble/Resonate/11.png'
import image12_1 from './assets/scribble/MindMatter/12.png'
import image12_2 from './assets/scribble/Overload/12.png'
import image12_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image12_4 from './assets/scribble/PeachesAndStrawbs/12.png'
import image12_5 from './assets/scribble/Abstract/12.png'
import image12_6 from './assets/scribble/Unfinished/12.png'
import image12_7 from './assets/scribble/Wasteland/12.png'
import image12_8 from './assets/scribble/Resonate/12.png'
import image13_1 from './assets/scribble/MindMatter/13.png'
import image13_2 from './assets/scribble/Overload/13.gif'
import image13_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image13_4 from './assets/scribble/PeachesAndStrawbs/13.png'
import image13_5 from './assets/scribble/Abstract/13.png'
import image13_6 from './assets/scribble/Unfinished/13.png'
import image13_7 from './assets/scribble/Wasteland/13.png'
import image13_8 from './assets/scribble/Resonate/13.png'
import image14_1 from './assets/scribble/MindMatter/14.png'
import image14_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image14_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image14_4 from './assets/scribble/PeachesAndStrawbs/14.png'
import image14_5 from './assets/scribble/Abstract/14.png'
import image14_6 from './assets/scribble/Unfinished/14.png'
import image14_7 from './assets/scribble/Wasteland/14.png'
import image14_8 from './assets/scribble/Resonate/14.png'
import image15_1 from './assets/scribble/MindMatter/15.png'
import image15_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image15_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image15_4 from './assets/scribble/PeachesAndStrawbs/15.png'
import image15_5 from './assets/scribble/Abstract/15.png'
import image15_6 from './assets/scribble/Unfinished/15.png'
import image15_7 from './assets/scribble/Wasteland/15.png'
import image15_8 from './assets/scribble/Resonate/15.png'
import image16_1 from './assets/scribble/MindMatter/16.png'
import image16_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image16_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image16_4 from './assets/scribble/PeachesAndStrawbs/16.png'
import image16_5 from './assets/scribble/Abstract/16.png'
import image16_6 from './assets/scribble/Unfinished/16.png'
import image16_7 from './assets/scribble/Wasteland/16.png'
import image16_8 from './assets/scribble/Resonate/16.png'
import image17_1 from './assets/scribble/MindMatter/17.png'
import image17_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image17_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image17_4 from './assets/scribble/PeachesAndStrawbs/17.png'
import image17_5 from './assets/scribble/Abstract/17.png'
import image17_6 from './assets/scribble/Unfinished/17.png'
import image17_7 from './assets/scribble/Wasteland/17.png'
import image17_8 from './assets/scribble/Resonate/17.png'
import image18_1 from './assets/scribble/MindMatter/18.png'
import image18_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image18_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image18_4 from './assets/scribble/PeachesAndStrawbs/18.png'
import image18_5 from './assets/scribble/Abstract/18.png'
import image18_6 from './assets/scribble/Unfinished/18.png'
import image18_7 from './assets/scribble/Wasteland/18.png'
import image18_8 from './assets/scribble/Resonate/18.png'
import image19_1 from './assets/scribble/MindMatter/19.png'
import image19_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image19_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image19_4 from './assets/scribble/PeachesAndStrawbs/19.png'
import image19_5 from './assets/scribble/Abstract/19.png'
import image19_6 from './assets/scribble/Unfinished/19.png'
import image19_7 from './assets/scribble/Wasteland/19.png'
import image19_8 from './assets/scribble/Resonate/19.png'
import image20_1 from './assets/scribble/MindMatter/20.png'
import image20_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image20_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image20_4 from './assets/scribble/PeachesAndStrawbs/20.png'
import image20_5 from './assets/scribble/Abstract/20.png'
import image20_6 from './assets/scribble/Unfinished/20.png'
import image20_7 from './assets/scribble/Wasteland/20.png'
import image20_8 from './assets/scribble/Resonate/20.png'
import image21_1 from './assets/scribble/MindMatter/21.png'
import image21_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image21_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image21_4 from './assets/scribble/PeachesAndStrawbs/21.png'
import image21_5 from './assets/scribble/Abstract/21.png'
import image21_6 from './assets/scribble/Unfinished/21.png'
import image21_7 from './assets/scribble/Wasteland/21.png'
import image21_8 from './assets/scribble/Resonate/21.png'
import image22_1 from './assets/scribble/MindMatter/22.png'
import image22_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image22_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image22_4 from './assets/scribble/PeachesAndStrawbs/22.png'
import image22_5 from './assets/scribble/Abstract/22.png'
import image22_6 from './assets/scribble/Unfinished/22.png'
import image22_7 from './assets/scribble/Wasteland/22.png'
import image22_8 from './assets/scribble/Resonate/22.png'
import image23_1 from './assets/scribble/MindMatter/23.png'
import image23_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image23_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image23_4 from './assets/scribble/PeachesAndStrawbs/23.png'
import image23_5 from './assets/scribble/Abstract/23.png'
import image23_6 from './assets/scribble/Unfinished/23.png'
import image23_7 from './assets/scribble/Wasteland/23.png'
import image23_8 from './assets/scribble/Resonate/23.png'
import image24_1 from './assets/scribble/MindMatter/24.png'
import image24_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image24_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image24_4 from './assets/scribble/PeachesAndStrawbs/24.png'
import image24_5 from './assets/scribble/Abstract/24.png'
import image24_6 from './assets/scribble/Unfinished/24.png'
import image24_7 from './assets/scribble/Wasteland/24.png'
import image24_8 from './assets/scribble/Resonate/24.png'
import image25_1 from './assets/scribble/MindMatter/25.png'
import image25_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image25_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image25_4 from './assets/scribble/PeachesAndStrawbs/25.png'
import image25_5 from './assets/scribble/Abstract/25.png'
import image25_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image25_7 from './assets/scribble/Wasteland/1.png'
import image25_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image26_1 from './assets/scribble/MindMatter/26.png'
import image26_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image26_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image26_4 from './assets/scribble/PeachesAndStrawbs/26.png'
import image26_5 from './assets/scribble/Abstract/26.png'
import image26_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image26_7 from './assets/scribble/Wasteland/2.png'
import image26_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image27_1 from './assets/scribble/MindMatter/27.png'
import image27_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image27_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image27_4 from './assets/scribble/PeachesAndStrawbs/27.png'
import image27_5 from './assets/scribble/Abstract/27.png'
import image27_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image27_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image27_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image28_1 from './assets/scribble/MindMatter/28.png'
import image28_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image28_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image28_4 from './assets/scribble/PeachesAndStrawbs/28.png'
import image28_5 from './assets/scribble/Abstract/28.png'
import image28_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image28_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image28_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image29_1 from './assets/scribble/MindMatter/29.png'
import image29_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image29_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image29_4 from './assets/scribble/PeachesAndStrawbs/29.png'
import image29_5 from './assets/scribble/Abstract/29.png'
import image29_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image29_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image29_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image30_1 from './assets/scribble/MindMatter/30.png'
import image30_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image30_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image30_4 from './assets/scribble/PeachesAndStrawbs/30.png'
import image30_5 from './assets/scribble/Abstract/30.png'
import image30_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image30_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image30_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image31_1 from './assets/scribble/MindMatter/31.png'
import image31_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image31_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image31_4 from './assets/scribble/PeachesAndStrawbs/31.png'
import image31_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image31_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image31_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image31_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image32_1 from './assets/scribble/MindMatter/32.png'
import image32_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image32_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image32_4 from './assets/scribble/PeachesAndStrawbs/32.png'
import image32_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image32_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image32_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image32_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image33_1 from './assets/scribble/MindMatter/33.png'
import image33_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image33_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image33_4 from './assets/scribble/PeachesAndStrawbs/33.png'
import image33_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image33_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image33_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image33_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image34_1 from './assets/scribble/MindMatter/34.png'
import image34_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image34_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image34_4 from './assets/scribble/PeachesAndStrawbs/34.png'
import image34_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image34_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image34_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image34_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image35_1 from './assets/scribble/MindMatter/35.png'
import image35_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image35_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image35_4 from './assets/scribble/PeachesAndStrawbs/35.png'
import image35_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image35_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image35_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image35_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image36_1 from './assets/scribble/MindMatter/36.png'
import image36_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image36_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image36_4 from './assets/scribble/PeachesAndStrawbs/36.png'
import image36_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image36_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image36_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image36_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image37_1 from './assets/scribble/MindMatter/37.png'
import image37_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image37_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image37_4 from './assets/scribble/PeachesAndStrawbs/37.png'
import image37_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image37_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image37_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image37_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image38_1 from './assets/scribble/MindMatter/38.png'
import image38_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image38_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image38_4 from './assets/scribble/PeachesAndStrawbs/38.png'
import image38_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image38_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image38_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image38_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image39_1 from './assets/scribble/MindMatter/39.png'
import image39_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image39_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image39_4 from './assets/scribble/PeachesAndStrawbs/39.png'
import image39_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image39_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image39_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image39_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image40_1 from './assets/scribble/MindMatter/40.png'
import image40_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image40_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image40_4 from './assets/scribble/PeachesAndStrawbs/40.png'
import image40_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image40_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image40_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image40_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image41_1 from './assets/scribble/MindMatter/41.png'
import image41_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image41_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image41_4 from './assets/scribble/PeachesAndStrawbs/41.png'
import image41_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image41_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image41_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image41_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image42_1 from './assets/scribble/MindMatter/42.png'
import image42_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image42_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image42_4 from './assets/scribble/PeachesAndStrawbs/42.png'
import image42_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image42_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image42_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image42_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image43_1 from './assets/scribble/MindMatter/43.png'
import image43_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image43_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image43_4 from './assets/scribble/PeachesAndStrawbs/43.png'
import image43_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image43_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image43_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image43_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image44_1 from './assets/scribble/MindMatter/44.png'
import image44_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image44_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image44_4 from './assets/scribble/PeachesAndStrawbs/44.png'
import image44_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image44_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image44_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image44_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image45_1 from './assets/scribble/MindMatter/45.png'
import image45_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image45_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image45_4 from './assets/scribble/PeachesAndStrawbs/45.png'
import image45_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image45_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image45_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image45_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image46_1 from './assets/scribble/MindMatter/46.png'
import image46_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image46_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image46_4 from './assets/scribble/PeachesAndStrawbs/46.png'
import image46_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image46_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image46_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image46_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image47_1 from './assets/scribble/MindMatter/47.png'
import image47_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image47_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image47_4 from './assets/scribble/PeachesAndStrawbs/47.png'
import image47_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image47_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image47_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image47_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image48_1 from './assets/scribble/MindMatter/48.png'
import image48_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image48_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image48_4 from './assets/scribble/PeachesAndStrawbs/48.png'
import image48_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image48_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image48_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image48_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image49_1 from './assets/scribble/MindMatter/49.png'
import image49_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image49_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image49_4 from './assets/scribble/PeachesAndStrawbs/49.png'
import image49_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image49_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image49_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image49_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image50_1 from './assets/scribble/MindMatter/50.png'
import image50_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image50_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image50_4 from './assets/scribble/PeachesAndStrawbs/50.png'
import image50_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image50_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image50_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image50_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image51_1 from './assets/scribble/MindMatter/51.png'
import image51_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image51_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image51_4 from './assets/scribble/PeachesAndStrawbs/51.png'
import image51_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image51_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image51_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image51_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image52_1 from './assets/scribble/MindMatter/52.png'
import image52_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image52_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image52_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image52_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image52_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image52_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image52_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image53_1 from './assets/scribble/MindMatter/53.png'
import image53_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image53_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image53_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image53_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image53_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image53_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image53_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image54_1 from './assets/scribble/MindMatter/54.png'
import image54_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image54_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image54_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image54_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image54_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image54_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image54_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image55_1 from './assets/scribble/MindMatter/55.png'
import image55_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image55_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image55_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image55_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image55_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image55_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image55_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image56_1 from './assets/scribble/MindMatter/56.png'
import image56_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image56_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image56_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image56_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image56_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image56_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image56_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image57_1 from './assets/scribble/MindMatter/57.png'
import image57_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image57_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image57_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image57_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image57_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image57_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image57_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image58_1 from './assets/scribble/MindMatter/58.png'
import image58_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image58_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image58_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image58_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image58_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image58_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image58_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image59_1 from './assets/scribble/MindMatter/59.png'
import image59_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image59_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image59_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image59_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image59_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image59_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image59_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image60_1 from './assets/scribble/MindMatter/60.png'
import image60_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image60_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image60_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image60_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image60_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image60_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image60_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image61_1 from './assets/scribble/MindMatter/61.png'
import image61_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image61_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image61_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image61_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image61_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image61_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image61_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image62_1 from './assets/scribble/MindMatter/62.png'
import image62_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image62_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image62_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image62_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image62_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image62_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image62_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image63_1 from './assets/scribble/MindMatter/63.png'
import image63_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image63_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image63_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image63_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image63_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image63_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image63_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image64_1 from './assets/scribble/MindMatter/64.png'
import image64_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image64_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image64_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image64_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image64_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image64_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image64_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image65_1 from './assets/scribble/MindMatter/65.png'
import image65_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image65_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image65_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image65_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image65_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image65_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image65_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image66_1 from './assets/scribble/MindMatter/66.png'
import image66_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image66_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image66_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image66_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image66_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image66_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image66_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image67_1 from './assets/scribble/MindMatter/67.png'
import image67_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image67_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image67_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image67_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image67_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image67_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image67_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image68_1 from './assets/scribble/MindMatter/68.gif'
import image68_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image68_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image68_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image68_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image68_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image68_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image68_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image69_1 from './assets/scribble/MindMatter/69.png'
import image69_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image69_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image69_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image69_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image69_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image69_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image69_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image70_1 from './assets/scribble/MindMatter/70.gif'
import image70_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image70_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image70_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image70_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image70_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image70_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image70_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image71_1 from './assets/scribble/MindMatter/71.gif'
import image71_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image71_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image71_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image71_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image71_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image71_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image71_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image72_1 from './assets/scribble/MindMatter/72.png'
import image72_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image72_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image72_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image72_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image72_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image72_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image72_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image73_1 from './assets/scribble/MindMatter/73.png'
import image73_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image73_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image73_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image73_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image73_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image73_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image73_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image74_1 from './assets/scribble/MindMatter/74.png'
import image74_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image74_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image74_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image74_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image74_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image74_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image74_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image75_1 from './assets/scribble/MindMatter/75.png'
import image75_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image75_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image75_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image75_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image75_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image75_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image75_8 from './assets/scribble/Resonate/scribbleplaceholder.png'
import image76_1 from './assets/scribble/MindMatter/76.png'
import image76_2 from './assets/scribble/Overload/scribbleplaceholder.png'
import image76_3 from './assets/scribble/Tales/TalesPlaceholder.png'
import image76_4 from './assets/scribble/PeachesAndStrawbs/scribbleplaceholder.png'
import image76_5 from './assets/scribble/Abstract/scribbleplaceholder.png'
import image76_6 from './assets/scribble/Unfinished/scribbleplaceholder.png'
import image76_7 from './assets/scribble/Wasteland/scribbleplaceholder.png'
import image76_8 from './assets/scribble/Resonate/scribbleplaceholder.png'

const traits = [
  { id: 1, image1: image1_1, image2: image1_2, image3: image1_3, image4: image1_4, image5: image1_5, image6: image1_6, image7: image1_7, image8: image1_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 2, image1: image2_1, image2: image2_2, image3: image2_3, image4: image2_4, image5: image2_5, image6: image2_6, image7: image2_7, image8: image2_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 3, image1: image3_1, image2: image3_2, image3: image3_3, image4: image3_4, image5: image3_5, image6: image3_6, image7: image3_7, image8: image3_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 4, image1: image4_1, image2: image4_2, image3: image4_3, image4: image4_4, image5: image4_5, image6: image4_6, image7: image4_7, image8: image4_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 5, image1: image5_1, image2: image5_2, image3: image5_3, image4: image5_4, image5: image5_5, image6: image5_6, image7: image5_7, image8: image5_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 6, image1: image6_1, image2: image6_2, image3: image6_3, image4: image6_4, image5: image6_5, image6: image6_6, image7: image6_7, image8: image6_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 7, image1: image7_1, image2: image7_2, image3: image7_3, image4: image7_4, image5: image7_5, image6: image7_6, image7: image7_7, image8: image7_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 8, image1: image8_1, image2: image8_2, image3: image8_3, image4: image8_4, image5: image8_5, image6: image8_6, image7: image8_7, image8: image8_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 9, image1: image9_1, image2: image9_2, image3: image9_3, image4: image9_4, image5: image9_5, image6: image9_6, image7: image9_7, image8: image9_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 10, image1: image10_1, image2: image10_2, image3: image10_3, image4: image10_4, image5: image10_5, image6: image10_6, image7: image10_7, image8: image10_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 11, image1: image11_1, image2: image11_2, image3: image11_3, image4: image11_4, image5: image11_5, image6: image11_6, image7: image11_7, image8: image11_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 12, image1: image12_1, image2: image12_2, image3: image12_3, image4: image12_4, image5: image12_5, image6: image12_6, image7: image12_7, image8: image12_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 13, image1: image13_1, image2: image13_2, image3: image13_3, image4: image13_4, image5: image13_5, image6: image13_6, image7: image13_7, image8: image13_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 14, image1: image14_1, image2: image14_2, image3: image14_3, image4: image14_4, image5: image14_5, image6: image14_6, image7: image14_7, image8: image14_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 15, image1: image15_1, image2: image15_2, image3: image15_3, image4: image15_4, image5: image15_5, image6: image15_6, image7: image15_7, image8: image15_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 16, image1: image16_1, image2: image16_2, image3: image16_3, image4: image16_4, image5: image16_5, image6: image16_6, image7: image16_7, image8: image16_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 17, image1: image17_1, image2: image17_2, image3: image17_3, image4: image17_4, image5: image17_5, image6: image17_6, image7: image17_7, image8: image17_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 18, image1: image18_1, image2: image18_2, image3: image18_3, image4: image18_4, image5: image18_5, image6: image18_6, image7: image18_7, image8: image18_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 19, image1: image19_1, image2: image19_2, image3: image19_3, image4: image19_4, image5: image19_5, image6: image19_6, image7: image19_7, image8: image19_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 20, image1: image20_1, image2: image20_2, image3: image20_3, image4: image20_4, image5: image20_5, image6: image20_6, image7: image20_7, image8: image20_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 21, image1: image21_1, image2: image21_2, image3: image21_3, image4: image21_4, image5: image21_5, image6: image21_6, image7: image21_7, image8: image21_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 22, image1: image22_1, image2: image22_2, image3: image22_3, image4: image22_4, image5: image22_5, image6: image22_6, image7: image22_7, image8: image22_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 23, image1: image23_1, image2: image23_2, image3: image23_3, image4: image23_4, image5: image23_5, image6: image23_6, image7: image23_7, image8: image23_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 24, image1: image24_1, image2: image24_2, image3: image24_3, image4: image24_4, image5: image24_5, image6: image24_6, image7: image24_7, image8: image24_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 25, image1: image25_1, image2: image25_2, image3: image25_3, image4: image25_4, image5: image25_5, image6: image25_6, image7: image25_7, image8: image25_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 26, image1: image26_1, image2: image26_2, image3: image26_3, image4: image26_4, image5: image26_5, image6: image26_6, image7: image26_7, image8: image26_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 27, image1: image27_1, image2: image27_2, image3: image27_3, image4: image27_4, image5: image27_5, image6: image27_6, image7: image27_7, image8: image27_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 28, image1: image28_1, image2: image28_2, image3: image28_3, image4: image28_4, image5: image28_5, image6: image28_6, image7: image28_7, image8: image28_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 29, image1: image29_1, image2: image29_2, image3: image29_3, image4: image29_4, image5: image29_5, image6: image29_6, image7: image29_7, image8: image29_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 30, image1: image30_1, image2: image30_2, image3: image30_3, image4: image30_4, image5: image30_5, image6: image30_6, image7: image30_7, image8: image30_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 31, image1: image31_1, image2: image31_2, image3: image31_3, image4: image31_4, image5: image31_5, image6: image31_6, image7: image31_7, image8: image31_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 32, image1: image32_1, image2: image32_2, image3: image32_3, image4: image32_4, image5: image32_5, image6: image32_6, image7: image32_7, image8: image32_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 33, image1: image33_1, image2: image33_2, image3: image33_3, image4: image33_4, image5: image33_5, image6: image33_6, image7: image33_7, image8: image33_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 34, image1: image34_1, image2: image34_2, image3: image34_3, image4: image34_4, image5: image34_5, image6: image34_6, image7: image34_7, image8: image34_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 35, image1: image35_1, image2: image35_2, image3: image35_3, image4: image35_4, image5: image35_5, image6: image35_6, image7: image35_7, image8: image35_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 36, image1: image36_1, image2: image36_2, image3: image36_3, image4: image36_4, image5: image36_5, image6: image36_6, image7: image36_7, image8: image36_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 37, image1: image37_1, image2: image37_2, image3: image37_3, image4: image37_4, image5: image37_5, image6: image37_6, image7: image37_7, image8: image37_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 38, image1: image38_1, image2: image38_2, image3: image38_3, image4: image38_4, image5: image38_5, image6: image38_6, image7: image38_7, image8: image38_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 39, image1: image39_1, image2: image39_2, image3: image39_3, image4: image39_4, image5: image39_5, image6: image39_6, image7: image39_7, image8: image39_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 40, image1: image40_1, image2: image40_2, image3: image40_3, image4: image40_4, image5: image40_5, image6: image40_6, image7: image40_7, image8: image40_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 41, image1: image41_1, image2: image41_2, image3: image41_3, image4: image41_4, image5: image41_5, image6: image41_6, image7: image41_7, image8: image41_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 42, image1: image42_1, image2: image42_2, image3: image42_3, image4: image42_4, image5: image42_5, image6: image42_6, image7: image42_7, image8: image42_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 43, image1: image43_1, image2: image43_2, image3: image43_3, image4: image43_4, image5: image43_5, image6: image43_6, image7: image43_7, image8: image43_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 44, image1: image44_1, image2: image44_2, image3: image44_3, image4: image44_4, image5: image44_5, image6: image44_6, image7: image44_7, image8: image44_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 45, image1: image45_1, image2: image45_2, image3: image45_3, image4: image45_4, image5: image45_5, image6: image45_6, image7: image45_7, image8: image45_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 46, image1: image46_1, image2: image46_2, image3: image46_3, image4: image46_4, image5: image46_5, image6: image46_6, image7: image46_7, image8: image46_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 47, image1: image47_1, image2: image47_2, image3: image47_3, image4: image47_4, image5: image47_5, image6: image47_6, image7: image47_7, image8: image47_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 48, image1: image48_1, image2: image48_2, image3: image48_3, image4: image48_4, image5: image48_5, image6: image48_6, image7: image48_7, image8: image48_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 49, image1: image49_1, image2: image49_2, image3: image49_3, image4: image49_4, image5: image49_5, image6: image49_6, image7: image49_7, image8: image49_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 50, image1: image50_1, image2: image50_2, image3: image50_3, image4: image50_4, image5: image50_5, image6: image50_6, image7: image50_7, image8: image50_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 51, image1: image51_1, image2: image51_2, image3: image51_3, image4: image51_4, image5: image51_5, image6: image51_6, image7: image51_7, image8: image51_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 52, image1: image52_1, image2: image52_2, image3: image52_3, image4: image52_4, image5: image52_5, image6: image52_6, image7: image52_7, image8: image52_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 53, image1: image53_1, image2: image53_2, image3: image53_3, image4: image53_4, image5: image53_5, image6: image53_6, image7: image53_7, image8: image53_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 54, image1: image54_1, image2: image54_2, image3: image54_3, image4: image54_4, image5: image54_5, image6: image54_6, image7: image54_7, image8: image54_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 55, image1: image55_1, image2: image55_2, image3: image55_3, image4: image55_4, image5: image55_5, image6: image55_6, image7: image55_7, image8: image55_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 56, image1: image56_1, image2: image56_2, image3: image56_3, image4: image56_4, image5: image56_5, image6: image56_6, image7: image56_7, image8: image56_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 57, image1: image57_1, image2: image57_2, image3: image57_3, image4: image57_4, image5: image57_5, image6: image57_6, image7: image57_7, image8: image57_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 58, image1: image58_1, image2: image58_2, image3: image58_3, image4: image58_4, image5: image58_5, image6: image58_6, image7: image58_7, image8: image58_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 59, image1: image59_1, image2: image59_2, image3: image59_3, image4: image59_4, image5: image59_5, image6: image59_6, image7: image59_7, image8: image59_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 60, image1: image60_1, image2: image60_2, image3: image60_3, image4: image60_4, image5: image60_5, image6: image60_6, image7: image60_7, image8: image60_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 61, image1: image61_1, image2: image61_2, image3: image61_3, image4: image61_4, image5: image61_5, image6: image61_6, image7: image61_7, image8: image61_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 62, image1: image62_1, image2: image62_2, image3: image62_3, image4: image62_4, image5: image62_5, image6: image62_6, image7: image62_7, image8: image62_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 63, image1: image63_1, image2: image63_2, image3: image63_3, image4: image63_4, image5: image63_5, image6: image63_6, image7: image63_7, image8: image63_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 64, image1: image64_1, image2: image64_2, image3: image64_3, image4: image64_4, image5: image64_5, image6: image64_6, image7: image64_7, image8: image64_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 65, image1: image65_1, image2: image65_2, image3: image65_3, image4: image65_4, image5: image65_5, image6: image65_6, image7: image65_7, image8: image65_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 66, image1: image66_1, image2: image66_2, image3: image66_3, image4: image66_4, image5: image66_5, image6: image66_6, image7: image66_7, image8: image66_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 67, image1: image67_1, image2: image67_2, image3: image67_3, image4: image67_4, image5: image67_5, image6: image67_6, image7: image67_7, image8: image67_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 68, image1: image68_1, image2: image68_2, image3: image68_3, image4: image68_4, image5: image68_5, image6: image68_6, image7: image68_7, image8: image68_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 69, image1: image69_1, image2: image69_2, image3: image69_3, image4: image69_4, image5: image69_5, image6: image69_6, image7: image69_7, image8: image69_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 70, image1: image70_1, image2: image70_2, image3: image70_3, image4: image70_4, image5: image70_5, image6: image70_6, image7: image70_7, image8: image70_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 71, image1: image71_1, image2: image71_2, image3: image71_3, image4: image71_4, image5: image71_5, image6: image71_6, image7: image71_7, image8: image71_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 72, image1: image72_1, image2: image72_2, image3: image72_3, image4: image72_4, image5: image72_5, image6: image72_6, image7: image72_7, image8: image72_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 73, image1: image73_1, image2: image73_2, image3: image73_3, image4: image73_4, image5: image73_5, image6: image73_6, image7: image73_7, image8: image73_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 74, image1: image74_1, image2: image74_2, image3: image74_3, image4: image74_4, image5: image74_5, image6: image74_6, image7: image74_7, image8: image74_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 75, image1: image75_1, image2: image75_2, image3: image75_3, image4: image75_4, image5: image75_5, image6: image75_6, image7: image75_7, image8: image75_8, nftName: 'Scribble', traitType: 'Scribble', },
  { id: 76, image1: image76_1, image2: image76_2, image3: image76_3, image4: image76_4, image5: image76_5, image6: image76_6, image7: image76_7, image8: image76_8, nftName: 'Scribble', traitType: 'Scribble', },



]
export default traits;
